name: proyecto-yesi-lab #PF
 
on:
 
  push:
    branches: [ release-Quality-sonar ]
  workflow_dispatch:
 
jobs:
 
  build:
   
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Descarga repositorio
        uses: actions/checkout@v3
 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Build Docker
        run: |
          docker build --tag yesibeth/curso-devsecops:latest . #Docker

      - name: Execute Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'yesibeth/curso-devsecops:latest'
          format: 'table'
          exit-code: 1
